# Default values for dz2.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
    repository: aroses/otus-dz2
    tag: latest

autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 4

ingress:
    enabled: true
    annotations:
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    hosts:
        - host: "arch.homework"
          paths:
              - path: "/"
                pathType: Prefix
                backend:
                    serviceName: dz2
                    servicePort: 8000

service:
    type: NodePort
    port: 8000

global:
    postgresql:
        enabled: true
        auth:
            username: myuser
            password: passwd
            database: myapp
        service:
            port: "5432"


